site_name: GlobeTalk Documentation
site_url: https://sitename.example

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo/logo.png
  favicon: assets/logo/logo.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: deep orange

plugins:
  - search

nav:
  - Home: index.md
  - Features: features.md
  - API:
      - Overview: api/index.md
      - Matchmaking API: api/matchmaking.md
      - Message API: api/message.md
      - Profile API: api/profile.md
      - Moderation API: api/moderation.md
  - UI Modules: ui.md
  - Database: database.md
  - Installation: installation.md
  - Usage: usage.md
  - Reasoning behind GlobeTalk Design: reasoning.md
  - Contributing: contributing.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - assets/styling/extra.css
